/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BinarySearch;

public class CC3 {
    public static int binarySearch (int[] arr, int t) {
        // l -> lower bound, u -> upper bound
        int l,u,mid;
        u = arr.length;
        l = 0;
        int idxFound = -1;

        while(l <= u) {
            mid = (int) (Math.floor((u + l) / 2));
            if(mid > arr.length-1) {
                break;
            }
            if (arr[mid] < t) {
                l = mid + 1;
            } else if (arr[mid] > t) {
                u = mid - 1;
            } else if (arr[mid] == t) {
                idxFound = mid;
                break;
            }
        }
        System.out.println("Returning index " + idxFound);
        return idxFound;
    }
}
