/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LinkedList;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void constructorTest() {
        assertNull(new LinkedList<Integer>());
        assertTrue(new LinkedListNode<Integer>(1, null).compareValue(1));
    }
}
