/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LinkedList;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testConstructor() {
        assertNull(new LinkedList<Integer>().head);
        assertTrue(new LinkedListNode<Integer>(1, null).compareValue(1));
    }

    @Test public void testInsert(){
        LinkedList<Integer> testList = new LinkedList();
        testList.insert(1);
        // Verify Value and that no next is assigned on first addition.
        assertTrue("Should be true |1|", testList.head.compareValue(1));
        assertFalse("Should be false |1|",testList.head.hasNext());
        // Verify head update and next is chained correctly.
        testList.insert(2);
        assertTrue("Should be true |2|", testList.head.compareValue(2));
        assertTrue("Should be true |2|", testList.head.next.compareValue(1));
    }

    @Test public void testIncludes() {
        LinkedList<Integer> testList = new LinkedList();
        testList.insert(1);
        testList.insert(2);
        testList.insert(3);
        testList.insert(4);
        testList.insert(5);
        assertTrue("Should find 1", testList.includes(1));
        assertTrue("Should find 4", testList.includes(4));
        assertTrue("Should find 5", testList.includes(5));
        assertFalse("Should not find 9", testList.includes(9));
        assertFalse("Should not find -1", testList.includes(-1));
    }

    @Test public void testToString() {
        LinkedList<Integer> testList = new LinkedList();
        testList.insert(3);
        testList.insert(2);
        testList.insert(1);
        assertEquals("Expected '1 2 3'", "1 2 3", testList.toString());
    }
}
