/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stacks_and_queues;

public class Stack<T> {
    protected Node top;

    public Stack() {
        this.top = null;
    }

    public T peek(){
        if(this.top != null) {
            return (T)this.top.data;
        }
        return null;
    }

    public void push(T data) {
        this.top = new Node(data, this.top);
    }

    public T pop() throws NullPointerException {
        if(this.top == null){
            throw new NullPointerException("No elements on Stack to pop");
        }
        T toRet = (T)this.top.data;
        this.top = this.top.next;
        return toRet;
    }

    private void printStack() {
        Node cur = this.top;
        System.out.println("Top");
        while(cur != null) {
            System.out.println(cur.data);
            cur = cur.next;
        }
        System.out.println("Bottom");
    }
}
