/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LinkedList;

class LinkedList<T> {
    // Data
    LinkedListNode head;

    // Constructor
    public LinkedList() {
        this.head = null;
    }

    public void insert(T value) {
        this.head = new LinkedListNode(value, this.head);
    }

    public boolean includes(T target) {
        LinkedListNode cur = this.head;
        while(cur != null) {
            if(cur.value.equals(target)) {
                return true;
            }
            cur = cur.next;
        }
        return false;
    }

    public String toString() {
        String strBuild = "";
        if(this.head == null) {
            return "Empty Linked List";
        }
        LinkedListNode<T> cur = this.head;
        while(cur != null) {
            System.out.print(cur.value + " ");
            cur = cur.next;
        }
        System.out.println();
        return strBuild;
    }

}

class LinkedListNode<T>{
    // Data
    T value;
    LinkedListNode<T> next;

    // Constructor
    public LinkedListNode(T value, LinkedListNode next) {
        this.value = value;
        this.next = next;
    }

    // Functions
    public boolean hasNext(){
        if(this.next != null) {
            return true;
        }
        return false;
    }

    public boolean compareNodeValues(LinkedListNode<T> compTo) {
        if(this.value.equals(compTo.value)) {
            return true;
        }
        return false;
    }
    public boolean compareValue(T compTo) {
        if(this.value == compTo) {
            return true;
        }
        return false;
    }

}
