/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array_shift;

import org.hamcrest.core.IsNot;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testEven() {
        assertArrayEquals(new int[]{1,2,5,3,4}, Library.array_shift(new int[]{1,2,3,4}, 5));
    }
    @Test public void testOdd() {
        assertArrayEquals(new int[]{1,2,3,7,4,5}, Library.array_shift(new int[]{1,2,3,4,5}, 7));
    }
    @Test public void testEmptyArray() {
        assertArrayEquals(new int[]{5}, Library.array_shift(new int[]{}, 5));
    }
    @Test public void testForFailure() {
        try{
            assertArrayEquals(new int[]{1,2,3,4}, Library.array_shift(new int[]{1,2,3,4}, 5));
        }
        catch(AssertionError e) {
            System.err.println("Expected failure: " + e);
        }
    }
}
